export const UI_TEXT = {
  gameTitle: 'CLICKER GAME',
  tapButton: 'TAP',
  storeTitle: 'STORE',
  metaUpgradesTitle: 'UPGRADES',
  /** @deprecated use metaUpgradesTitle */
  boostsTitle: 'UPGRADES',
  settingsTitle: 'SETTINGS',
  tabs: ['STORE', 'TAP', 'UPGRADE'],
  sound: 'SOUND',
  soundDescription: 'Sound effects for purchases',
  vibration: 'VIBRATION',
  vibrationDescription: 'Light feedback for purchases',
  on: 'ON',
  off: 'OFF',
  welcomeBack: 'WELCOME BACK',
  offlineEarnings: 'OFFLINE EARNINGS',
  continue: 'CONTINUE',
  start: 'Click to start',
  buy: 'BUY',
  owned: 'OWNED',
  locked: 'LOCKED',
  unlockHint: 'Keep progressing to unlock',
  metaFallbackUpgrade: 'Upgrade',
  metaOwnGenerator: 'Own {count} of {label}',
  metaOwnTotal: 'Own {count} generators total',
  metaReachTaps: 'Reach {count} taps',
  metaOwnPaired: 'Own {left} + {right} paired generators',
  metaEffectGenerator: '{label} x{mult}',
  metaEffectGlobal: 'All production x{mult}',
  metaEffectClickCps: 'Tap +{pct}% of CPS',
  metaEffectSynergy: 'Paired generators boost each other',
  tapPowerEffect: '+{value} tap power',
  autoTapEffect: '+{value} click / {seconds}s',
  generatorEffect: '+{value} per second',
};
